const express = require("express");
const axios = require("axios");
const Joi = require("joi");

const router = express.Router();

const payloadSchema = Joi.object({
    board: Joi.string().required(),
    grade: Joi.string().required(),
    subject: Joi.string().required(),
    subSubject: Joi.string().optional().allow(""),
    unit: Joi.string().optional().allow(""),
    chapter: Joi.string().required(),
    topics: Joi.array()
        .items(
            Joi.object({
                name: Joi.string().required(),
                concepts: Joi.array().items(Joi.string().required()).required(),
            })
        )
        .min(1)
        .required(),
    sessionType: Joi.string().required(),
    noOfSession: Joi.number().integer().required(),
    duration: Joi.number().integer().required(),
});

router.post("/dynamicLP", async (req, res) => {
    try {
        const { error } = payloadSchema.validate(req.body);
        if (error) {
            console.error("Validation error:", error.details);
            return res.status(400).json({ message: error.details[0].message });
        }

        const payload = req.body;
        console.log("Payload sent to Python service:", payload);

        const pythonServiceUrl = "https://dynamiclp.up.school/generate-lesson-plan";
        const response = await axios.post(pythonServiceUrl, payload);

        if (!response.data || !response.data.lesson_plan) {
            console.error("Python service returned no lesson plan:", response.data);
            return res.status(500).json({
                message: "Lesson plan not generated by Python service.",
                details: response.data,
            });
        }

        res.status(200).json(response.data);
    } catch (error) {
        console.error("Error in dynamicLP route:", error.message);
        if (error.response) {
            console.error("Python service error:", error.response.data);
            return res.status(error.response.status).json({
                message: "Python service error",
                details: error.response.data,
            });
        }
        res.status(500).json({
            message: "Failed to generate lesson plan. Please try again.",
            error: error.message,
        });
    }
});

module.exports = router;
